import { Sticker } from "./BaseItem"

export const CloseOne = new Sticker("Close One", "Sport", "t_ui_CloseOne.png")
export const Happy = new Sticker("Happy", "Sport", "t_ui_Happy1.png")
export const Heart = new Sticker("Heart", "Special", "t_ui_Heart1.png")
export const Sad = new Sticker("Sad", "Sport", "t_ui_Sad1.png")
export const Sorry = new Sticker("Sorry", "Base", "t_ui_Sorry1.png")
export const ThumbsUp = new Sticker("Thumbs Up", "Sport", "t_ui_ThumbsUp1.png")
export const Devastated = new Sticker("Devastated", "Sport", "t_ui_Devestated.png")
export const GLHF = new Sticker("GLHF", "Sport", "t_ui_GLHF.png")
export const Nice = new Sticker("Nice", "Sport", "t_ui_Nice1.png")
export const Nooo = new Sticker("Nooo", "Sport", "t_ui_No1.png")
export const Nooo2 = new Sticker("Nooo", "Sport", "t_ui_No2.png")
export const OMG = new Sticker("OMG", "Sport", "t_ui_OMG1.png")
export const Oof = new Sticker("Oof", "Sport", "t_ui_Oof1.png")
export const Oof2 = new Sticker("Oof", "Sport", "t_ui_Oof2.png")
export const TakeTheShot = new Sticker("Take the Shot", "Sport", "t_ui_TakeTheShot1.png")
export const Wow = new Sticker("Wow", "Sport", "t_ui_Wow1.png")
export const EggEyes = new Sticker("Egg Eyes", "Sport", "t_ui_Egg_Eyes.png")
export const NiceShot = new Sticker("Nice Shot", "Base", "t_ui_NiceShot1.png")
export const WhatAPlay = new Sticker("What A Play", "Sport", "t_ui_WhatAplay.png")
export const NiceBlock = new Sticker("Nice Block", "Sport", "t_ui_NiceBlock.png")
export const Siiick = new Sticker("Siiick", "Sport", "t_ui_Siiick.png")
export const WeGotThis = new Sticker("We Got This", "Sport", "t_ui_WeGotThis.png")
export const EggHearts = new Sticker("Egg Hearts", "Sport", "t_ui_Egg_Hearts.png")
export const EggMoney = new Sticker("Egg Money", "Sport", "t_ui_Egg_Money.png")
export const EggTriumph = new Sticker("Egg Triumph", "Sport", "t_ui_Egg_Triumph.png")
export const EggCracked = new Sticker("Egg Cracked", "Sport", "t_ui_Egg_Cracked.png")
export const EggParty = new Sticker("Egg Party", "Sport", "t_ui_Egg_Party.png")
export const EggShades = new Sticker("Egg Shades", "Sport", "t_ui_Egg_Shades.png")
export const Calculated = new Sticker("Calculated", "Base", "t_ui_Calculated1.png")
export const Curse = new Sticker("Curse", "Base", "t_ui_Angry1.png")
export const GG = new Sticker("GG", "Base", "t_ui_GG1.png")
export const GotIt = new Sticker("Got It", "Base", "t_ui_GotIt1.png")
export const GreatPass = new Sticker("Great Pass!", "Base", "t_ui_quick_GreatPass.png")
export const InPosition = new Sticker("In Position", "Base", "t_ui_InPosition1.png")
export const NiceShot2 = new Sticker("Nice Shot", "Sport", "t_ui_NiceShot2.png")
export const NoProblem = new Sticker("No Problem", "Base", "t_ui_NoProblem1.png")
export const Oops = new Sticker("Oops", "Base", "t_ui_Oops1.png")
export const Sorry2 = new Sticker("Sorry", "Sport", "t_ui_Sorry2.png")
export const Thanks = new Sticker("Thanks!", "Base", "t_ui_Thanks1.png")
export const WhatASave = new Sticker("What A Save", "Base", "t_ui_WhataSave1.png")
export const GoldenSmile = new Sticker("Golden Smile", "Black Market", "t_ui_GoldenSmile.png")
export const GoldenFrown = new Sticker("Golden Frown", "Black Market", "t_ui_GoldenFrown.png")
export const GoldenGrump = new Sticker("Golden Grump", "Black Market", "t_ui_GoldenGrump.png")
export const EggHappy = new Sticker("Happy Egg", "Sport", "t_ui_Egg_Happy.png")
export const EggAngry = new Sticker("Angry Egg", "Sport", "t_ui_Egg_Angry.png")
export const EggSad = new Sticker("Sad Egg", "Sport", "t_ui_Egg_Sad.png")
export const EggHappyDev = new Sticker("Dev Happy Egg", "Developer", "t_ui_Egg_Dev_Happy.png")
export const EggAngryDev = new Sticker("Dev Angry Egg", "Developer", "t_ui_Egg_Dev_Angry.png")
export const EggSadDev = new Sticker("Dev Sad Egg", "Developer", "t_ui_Egg_Dev_Sad.png")

// S17
export const Sharp = new Sticker("Sharp", "Sport", "t_ui_Sticker_Shark.png")
export const EggSummer = new Sticker("Summer Egg", "Sport", "t_ui_egg_summer.png")
export const Outch = new Sticker("Outch", "Sport", "t_ui_OutchCactus.png")
export const YouGotMe = new Sticker("You Got Me", "Sport", "t_ui_sticker_YouGotMe.png")

// S18
export const PixelEgg = new Sticker("Pixel Egg", "Sport", "t_ui_Sticker_PixelEgg.png")
export const Lucky = new Sticker("Lucky", "Special", "t_ui_Sticker_Lucky.png")
export const PeaceToYou = new Sticker("Peace To You", "Sport", "t_ui_Sticker_PeaceToYou.png")
export const Nani = new Sticker("Nani", "Deluxe", "t_ui_Sticker_Nani.png")

// S19
export const SnakeLantern = new Sticker("Snake Lantern", "Sport", "t_ui_sticker_SnakeLantern.png")
export const WinterEgg = new Sticker("Winter Egg", "Sport", "t_ui_sticker_SantaEgg.png")
export const Help = new Sticker("HELP", "Special", "t_ui_Sticker_HELP.png")

// S20
export const SOS = new Sticker("SOS", "Special", "t_ui_sticker_SOS.png")
export const Great = new Sticker("Great", "Special", "t_ui_sticker_gr8.png")
export const AstroDoggo = new Sticker("Astro Doggo", "Deluxe", "t_ui_sticker_AstroDoggo.png")

// S21
export const MamaMia = new Sticker("Mama Mia", "Luxury", "t_ui_sticker_MamaMia.png")

// Season Rewards
export const S1Bronze = new Sticker("S1 Bronze", "Luxury", "t_ui_S1_Bronze.png")
export const S1Silver = new Sticker("S1 Silver", "Luxury", "t_ui_S1_Silver.png")
export const S1Gold = new Sticker("S1 Gold", "Luxury", "t_ui_S1_Gold.png")
export const S1Platinum = new Sticker("S1 Platinum", "Luxury", "t_ui_S1_Platinum.png")
export const S1Diamond = new Sticker("S1 Diamond", "Luxury", "t_ui_S1_Diamond.png")
export const S1Champion = new Sticker("S1 Champion", "Luxury", "t_ui_S1_Champion.png")
export const S1GrandChampion = new Sticker("S1 Grand Champion", "Luxury", "t_ui_S1_GrandChampion.png")
export const S4Bronze = new Sticker("S4 Bronze", "Luxury", "Quickchat_S4_Bronze.png")
export const S4Silver = new Sticker("S4 Silver", "Luxury", "Quickchat_S4_Silver.png")
export const S4Gold = new Sticker("S4 Gold", "Luxury", "Quickchat_S4_Gold.png")
export const S4Platinum = new Sticker("S4 Platinum", "Luxury", "Quickchat_S4_Platinum.png")
export const S4Diamond = new Sticker("S4 Diamond", "Luxury", "Quickchat_S4_Diamond.png")
export const S4Champion = new Sticker("S4 Champion", "Luxury", "Quickchat_S4_Champion.png")
export const S4GrandChampion = new Sticker("S4 Grand Champion", "Luxury", "Quickchat_S4_GrandChampion.png")
